server:
  port:9003

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.10:7001/eureka,http://127.0.0.1:7002/eureka

spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          skipSslValidation: true # 跳过ssl认证
          uri: https://github.com/heartJJ/config-repository
          search-paths:
            - config-repository # 搜索目录
      label: master # 分支